### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by vanessakindell** [flathub/com.tdameritrade.ThinkOrSwim#3] opened 2022-06-12 19:38 UTC
OS: System76 Pop!_os

Commands: flatpak install com.tdameritrade.ThinkOrSwim 
flatpak run com.tdameritrade.ThinkOrSwim

Result: he installation directory has been set to /home/[my home folder]/thinkorswim.
Extracting files ...
Finishing installation ...
sed: can't read /home/[my home folder]/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/workspace.*.tos.prod.xml: No such file or directory
/app/bin/thinkorswim: line 15: /home/[my home folder]/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/thinkorswim: No such file or directory

Nothing loads in the GUI at all.

**Comment by jmac09** [comment] 2022-06-15 00:35
I have the same issue when trying to install ThinkOrSwim using flatpak on Ubuntu 20.04.4 LTS (Focal Fossa).  

Clicking in TOS icon to launch the program does nothing, and when running flatpak run com.tdameritrade.ThinkOrSwim I get the same error as mentioned above.  

Please fix the issue.  Thanks!

**Comment by jkoelker** [comment] 2022-06-15 01:13
Can you see if the process is running? The sed is trying to fix java window re-homing on wayland, but since its a fresh install, it will fail, but it should still launch the process.

If it is running, then it would appear to be the re-homing issue with java apps, through trial and error I found that on an existing install, editing the workspace and removing the `ACCOUNT_MODELS` blob works around the issue (which is what the sed tries to do https://github.com/flathub/com.tdameritrade.ThinkOrSwim/blob/master/thinkorswim#L12).

Best I can recommend is to kill the process, and relaunch it a few times, I've found that *eventually* it will launch and after that the workspace editing trick will get it to launch. Unforts with it being closed source there's nothing I can do about fixing the real issue. I've notified ToS support, you might try the same, but linux and non osx unix variants are technically unsupported by them.

**Comment by jmac09** [comment] 2022-06-15 01:49
I have the same issue as [vanessakindell](https://github.com/vanessakindell).

I check my processes, and I don't have any open SED processes running.   It looks like the home directory is not getting set.  

Here is my error:

-----------------------
flatpak run com.tdameritrade.ThinkOrSwim 
Starting Installer ...
The installation directory has been set to /home/[username]/thinkorswim.
Extracting files ...
Finishing installation ...
sed: can't read /home/[username]/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/workspace.*.tos.prod.xml: No such file or directory
/app/bin/thinkorswim: line 15: /home/[username]/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/thinkorswim: No such file or directory
-----------------------

The directory /home/[username]/thinkorswim is not getting created.   

I modified my .profile file to include the following and logged out and then back.  

export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}

then I reran:
flatpak run com.tdameritrade.ThinkOrSwim 

and got the same error.   

In the master sh file (https://github.com/flathub/com.tdameritrade.ThinkOrSwim/blob/master/thinkorswim), I see it is calling 
/app/extra/thinkorswim_installer.sh, but I can't find this file anywhere on my system except here:

/var/lib/flatpak/.removed/com.tdameritrade.ThinkOrSwim-e379ba0b5553a7760357b0379f8b3597940b316417236f175606ea7173b7bf87/files/extra/thinkorswim_installer.sh
/var/lib/flatpak/app/com.tdameritrade.ThinkOrSwim/x86_64/stable/e379ba0b5553a7760357b0379f8b3597940b316417236f175606ea7173b7bf87/files/extra/thinkorswim_installer.sh

**Comment by jkoelker** [comment] 2022-06-15 14:32
`sed` is the process that is ending with the error, it will be a `java` process and look something like:

```
/app/jre/bin/java -Dinstall4j.jvmDir=/app/jre -Dexe4j.moduleName=/home/jkoelker/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/thinkorswim
```

**Comment by vanessakindell** [comment] 2022-06-29 01:00
I found a workaround: The whole issue is that the program wasn't given the home folder filesystem access. All you have to do to get it working is install FlatSeal and change that setting and it works.

Tested under Pop! OS and Linux Mint.

**Comment by tidux** [comment] 2022-08-12 15:49
The workaround via Flatseal does not work on Fedora 36.

**Comment by jmac09** [comment] 2022-08-21 01:25
Hi Vanessa, what exactly did you do in Flatseal to get thinkorswim to run on flatpak?   Under the TOS app in flatseal, i went to filesystem and toggled on filesystem=home, but TOS still didn't work.    

Thanks,
Jason

**Comment by kinghat** [comment] 2022-08-25 17:51
same issue on manjaro stable channel.

**Comment by eli-xciv** [comment] 2022-09-12 00:45
For everyone who wants to run this flatpak and is running into this issue. There seems to be a disconnect at the installer where the thinkorswim script adds the `-dir`. 

I was able to handjam the install for the flatpak; testing on Fedora 36

```
# You may need to install a run time for this work.
flatpak install org.freedesktop.Sdk//20.08

flatpak run --command=sh  com.tdameritrade.ThinkOrSwim

# Run the installer 
sh /app/extra/thinkorswim_installer.sh

exit
flatpak run com.tdameritrade.ThinkOrSwim
```

This installer will give you a prompt, during the installation on where to install TOS. 
enter `/home/<your_username>/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim`

Once it's installed into the app, it'll run normally every flatpak run after.

**Comment by rohsaurus** [comment] 2022-09-15 14:12
After doing the config change with flatseal, I then had to open up thinkorswim manually using the terminal. I went to where it was installed (in my case ~/thinkorswim) and just ran ./thinkorswim. I let it do its updates, and after closing and restarting a few times, the desktop shortcut worked for me. However, it doesn't work through the pop os launcher or dock.

**Comment by SaltyCybernaut** [comment] 2022-10-09 03:36
I was able to get the TOS Flatpak working on Pop!_OS 22.04 LTS by following the steps below. I believe the root cause is that the installer script _**thinkorswim_installer.sh**_ and the executable bundled inside the script assume different defaults for the installation directory.
### Install the TOS Flatpak
`flatpak install com.tdameritrade.ThinkOrSwim`
note: I installed this as a 'user' Flatpak (option 2 for me)
### Attempt to run TOS and watch it fail
`flatpak run  com.tdameritrade.ThinkOrSwim`
>Starting Installer ...
>The installation directory has been set to /home/<your_user_directory>/thinkorswim.
>Extracting files ...
>Finishing installation ...
>sed: can't read /home/<your_user_directory>/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/workspace.*.tos.prod.xml: No such file or directory
>/app/bin/thinkorswim: line 15: /home/<your_user_directory>/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/>thinkorswim: No such file or directory
The installation directory being set to _**/home/<your_user_directory>/thinkorswim**_ is why it fails.
### Give TOS access to your home folder using FlatSeal (this might be optional)
![temp](https://user-images.githubusercontent.com/7234219/194735573-0aca4cda-10ab-452b-9413-a723d270ea03.png)
### Enter the TOS 'container'
`flatpak run --command=sh  com.tdameritrade.ThinkOrSwim`
### Run the TOS installer
`sh /app/extra/thinkorswim_installer.sh`
### Choose a custom installation
![temp2](https://user-images.githubusercontent.com/7234219/194736505-941c3883-c4e4-4c6c-a275-4c0fbe544116.png)
### Set the installation directory to _**/home/<your_user_directory>/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim**_
![temp3](https://user-images.githubusercontent.com/7234219/194736533-b5a4a0b8-c804-492f-a8c3-cfcff6fa4a2d.png)
### Exit the TOS 'container'
`exit`
### Start TOS from the GUI or Terminal
`flatpak run  com.tdameritrade.ThinkOrSwim`

**Comment by uberscientist** [comment] 2022-10-10 17:22
@SaltyCybernaut great write up, I didn't have to do the FlatSeal permission changing since it should only be touching the flatpak 'container' dir that needs to be updated, dunno how this issue isn't an issue for others!

**Comment by Aelieth** [comment] 2024-07-17 20:47
Getting a Java error on my system and another. 

Zulu OpenJDK 17.0.10 is required to start the application. Please update Java and ensure it is the first JRE available in your system path.

![Screenshot_20240717_154527](https://github.com/user-attachments/assets/3c9c858a-4c7c-4013-803a-3e66a640b15e)

**Comment by uberscientist** [comment] 2024-07-17 21:27
> Getting a Java error on my system and another.
> 
> Zulu OpenJDK 17.0.10 is required to start the application. Please update Java and ensure it is the first JRE available in your system path.

I don't think we have Zulu OpenJDK flatpaks unfortunately (please if someone knows of flatpak, link it here), but even when I tried with an install on my base system, I got an error. I used [sdkman!](https://sdkman.io/install) to install Zulu OpenJDK 17.0.10:
`$ sdk install java 17.0.10-zulu`

and then installed thinkorswim using their install script, I get an unhelpful error:
![image](https://github.com/user-attachments/assets/442092f8-40cd-4db7-bef2-fb998a9192f0)

really wish we could get something to work on linux

**Comment by jkoelker** [comment] 2024-07-18 01:30
I updated the build to use openjdk17 and fixed the persiting of the installer (since it looks like `-dir` support isn't coming back). Please test https://github.com/flathub/com.tdameritrade.ThinkOrSwim/pull/10 and let me know if it works for you, it obvs works on my machines :grinning:.

**Closed as completed** 2024-07-18 22:03 UTC
